# Generated by Django 3.1.5 on 2021-01-20 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuronetprediction',
            name='treatment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neuronet_prediction', to='web.treatment'),
        ),
    ]
