# Generated by Django 3.1.5 on 2021-01-20 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210120_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neuronetprediction',
            name='treatment',
        ),
        migrations.AddField(
            model_name='treatment',
            name='predict',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.neuronetprediction'),
        ),
    ]
