# Generated by Django 3.1.5 on 2021-01-20 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_auto_20210120_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=100)),
                ('treatment_tactics', models.TextField()),
                ('tactics_if_agree', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='diagnoses',
            field=models.ManyToManyField(blank=True, to='web.Diagnosis'),
        ),
        migrations.AlterField(
            model_name='treatment',
            name='temporary_contraindications',
            field=models.ManyToManyField(blank=True, to='web.TemporaryContraindications'),
        ),
        migrations.AddField(
            model_name='neuronetprediction',
            name='recommend_text',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='web.recommendtext'),
            preserve_default=False,
        ),
    ]
