# Generated by Django 3.1.5 on 2021-01-24 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20210124_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuronetprediction',
            name='recommend_text',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.recommendtext'),
        ),
    ]
