# Generated by Django 3.1.5 on 2022-12-07 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0009_auto_20210126_0106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=45)),
                ('gender', models.PositiveSmallIntegerField()),
                ('birthday', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CorrectionalWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prisoner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.PositiveSmallIntegerField()),
                ('birthday', models.DateField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.admin')),
                ('articles', models.ManyToManyField(to='web.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('visited', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PrisonerHasCorrectionalWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.admin')),
                ('correctional_work_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.correctionalwork')),
                ('prisoner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.prisoner')),
            ],
        ),
        migrations.AddField(
            model_name='prisoner',
            name='correctional_works',
            field=models.ManyToManyField(through='web.PrisonerHasCorrectionalWork', to='web.CorrectionalWork'),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='records',
            field=models.ManyToManyField(to='web.Record'),
        ),
        migrations.AddField(
            model_name='prisoner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meetingcol', models.CharField(max_length=45)),
                ('date', models.DateTimeField()),
                ('theme', models.CharField(max_length=100)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.admin')),
                ('prisoner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.prisoner')),
            ],
        ),
    ]
